<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tour/v1/tour_schedule.proto

namespace Travel\Proto\TourSchedule\V1\Metadata;

class TourSchedule
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xB9\x07\x0A\x1Btour/v1/tour_schedule.proto\x12\x07tour.v1\"H\x0A\x1AGetTourScheduleByIdRequest\x12\x18\x0A\x10tour_schedule_id\x18\x01 \x01(\x09\x12\x10\x0A\x08language\x18\x02 \x01(\x09\"\x9E\x02\x0A\x18TourScheduleByIdResponse\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x0F\x0A\x07tour_id\x18\x02 \x01(\x09\x12\x12\x0A\x0Astart_date\x18\x03 \x01(\x09\x12\x10\x0A\x08end_date\x18\x04 \x01(\x09\x12\x18\x0A\x10min_participants\x18\x05 \x01(\x05\x12\x18\x0A\x10max_participants\x18\x06 \x01(\x05\x12\x17\x0A\x0Favailable_slots\x18\x07 \x01(\x05\x12\x14\x0A\x0Cbooked_slots\x18\x08 \x01(\x05\x12\x10\x0A\x08guide_id\x18\x09 \x01(\x09\x12\x12\x0A\x0Atour_title\x18\x0A \x01(\x09\x12\x0E\x0A\x06status\x18\x0B \x01(\x05\x12\x12\x0A\x0Acreated_at\x18\x0C \x01(\x03\x12\x12\x0A\x0Aupdated_at\x18\x0D \x01(\x03\"W\x0A\"GetListTourScheduleByTourIdRequest\x12\x0F\x0A\x07tour_id\x18\x01 \x01(\x09\x12\x0E\x0A\x06status\x18\x02 \x01(\x05\x12\x10\x0A\x08language\x18\x03 \x01(\x09\"\x8D\x01\x0A ListTourScheduleByTourIdResponse\x129\x0A\x0Etour_schedules\x18\x01 \x03(\x0B2!.tour.v1.TourScheduleByIdResponse\x12\x0D\x0A\x05total\x18\x02 \x01(\x05\x12\x0C\x0A\x04page\x18\x03 \x01(\x05\x12\x11\x0A\x09page_size\x18\x04 \x01(\x052\xEB\x01\x0A\x13TourScheduleService\x12]\x0A\x13GetTourScheduleById\x12#.tour.v1.GetTourScheduleByIdRequest\x1A!.tour.v1.TourScheduleByIdResponse\x12u\x0A\x1BGetListTourScheduleByTourId\x12+.tour.v1.GetListTourScheduleByTourIdRequest\x1A).tour.v1.ListTourScheduleByTourIdResponseBG\xCA\x02\x1CTravel\\Proto\\TourSchedule\\V1\xE2\x02%Travel\\Proto\\TourSchedule\\V1\\Metadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

