<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tour/v1/tour_schedule.proto

namespace Travel\Proto\TourSchedule\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tour.v1.GetListTourScheduleByTourIdRequest</code>
 */
class GetListTourScheduleByTourIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tour_id = 1;</code>
     */
    protected $tour_id = '';
    /**
     * Generated from protobuf field <code>int32 status = 2;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string language = 3;</code>
     */
    protected $language = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tour_id
     *     @type int $status
     *     @type string $language
     * }
     */
    public function __construct($data = NULL) {
        \Travel\Proto\TourSchedule\V1\Metadata\TourSchedule::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tour_id = 1;</code>
     * @return string
     */
    public function getTourId()
    {
        return $this->tour_id;
    }

    /**
     * Generated from protobuf field <code>string tour_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTourId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tour_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string language = 3;</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>string language = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->language = $var;

        return $this;
    }

}

