<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tour/v1/tour_schedule.proto

namespace Travel\Proto\TourSchedule\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tour.v1.TourScheduleByIdResponse</code>
 */
class TourScheduleByIdResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string tour_id = 2;</code>
     */
    protected $tour_id = '';
    /**
     * Generated from protobuf field <code>string start_date = 3;</code>
     */
    protected $start_date = '';
    /**
     * Generated from protobuf field <code>string end_date = 4;</code>
     */
    protected $end_date = '';
    /**
     * Generated from protobuf field <code>int32 min_participants = 5;</code>
     */
    protected $min_participants = 0;
    /**
     * Generated from protobuf field <code>int32 max_participants = 6;</code>
     */
    protected $max_participants = 0;
    /**
     * Generated from protobuf field <code>int32 available_slots = 7;</code>
     */
    protected $available_slots = 0;
    /**
     * Generated from protobuf field <code>int32 booked_slots = 8;</code>
     */
    protected $booked_slots = 0;
    /**
     * Generated from protobuf field <code>string guide_id = 9;</code>
     */
    protected $guide_id = '';
    /**
     * Generated from protobuf field <code>string tour_title = 10;</code>
     */
    protected $tour_title = '';
    /**
     * Generated from protobuf field <code>int32 status = 11;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>int64 created_at = 12;</code>
     */
    protected $created_at = 0;
    /**
     * Generated from protobuf field <code>int64 updated_at = 13;</code>
     */
    protected $updated_at = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $tour_id
     *     @type string $start_date
     *     @type string $end_date
     *     @type int $min_participants
     *     @type int $max_participants
     *     @type int $available_slots
     *     @type int $booked_slots
     *     @type string $guide_id
     *     @type string $tour_title
     *     @type int $status
     *     @type int|string $created_at
     *     @type int|string $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \Travel\Proto\TourSchedule\V1\Metadata\TourSchedule::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tour_id = 2;</code>
     * @return string
     */
    public function getTourId()
    {
        return $this->tour_id;
    }

    /**
     * Generated from protobuf field <code>string tour_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTourId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tour_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string start_date = 3;</code>
     * @return string
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    /**
     * Generated from protobuf field <code>string start_date = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string end_date = 4;</code>
     * @return string
     */
    public function getEndDate()
    {
        return $this->end_date;
    }

    /**
     * Generated from protobuf field <code>string end_date = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 min_participants = 5;</code>
     * @return int
     */
    public function getMinParticipants()
    {
        return $this->min_participants;
    }

    /**
     * Generated from protobuf field <code>int32 min_participants = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMinParticipants($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_participants = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_participants = 6;</code>
     * @return int
     */
    public function getMaxParticipants()
    {
        return $this->max_participants;
    }

    /**
     * Generated from protobuf field <code>int32 max_participants = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxParticipants($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_participants = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 available_slots = 7;</code>
     * @return int
     */
    public function getAvailableSlots()
    {
        return $this->available_slots;
    }

    /**
     * Generated from protobuf field <code>int32 available_slots = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setAvailableSlots($var)
    {
        GPBUtil::checkInt32($var);
        $this->available_slots = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 booked_slots = 8;</code>
     * @return int
     */
    public function getBookedSlots()
    {
        return $this->booked_slots;
    }

    /**
     * Generated from protobuf field <code>int32 booked_slots = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setBookedSlots($var)
    {
        GPBUtil::checkInt32($var);
        $this->booked_slots = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string guide_id = 9;</code>
     * @return string
     */
    public function getGuideId()
    {
        return $this->guide_id;
    }

    /**
     * Generated from protobuf field <code>string guide_id = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setGuideId($var)
    {
        GPBUtil::checkString($var, True);
        $this->guide_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tour_title = 10;</code>
     * @return string
     */
    public function getTourTitle()
    {
        return $this->tour_title;
    }

    /**
     * Generated from protobuf field <code>string tour_title = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setTourTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->tour_title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 11;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 created_at = 12;</code>
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>int64 created_at = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at = 13;</code>
     * @return int|string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated_at = $var;

        return $this;
    }

}

