<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tour/v1/tour.proto

namespace Travel\Proto\Tour\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request messages
 *
 * Generated from protobuf message <code>tour.v1.GetTourByIdRequest</code>
 */
class GetTourByIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tour_id = 1;</code>
     */
    protected $tour_id = '';
    /**
     * Generated from protobuf field <code>string language = 2;</code>
     */
    protected $language = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tour_id
     *     @type string $language
     * }
     */
    public function __construct($data = NULL) {
        \Travel\Proto\Tour\V1\Metadata\Tour::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tour_id = 1;</code>
     * @return string
     */
    public function getTourId()
    {
        return $this->tour_id;
    }

    /**
     * Generated from protobuf field <code>string tour_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTourId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tour_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string language = 2;</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>string language = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->language = $var;

        return $this;
    }

}

