<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tour/v1/tour.proto

namespace Travel\Proto\Tour\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tour.v1.ListToursResponse</code>
 */
class ListToursResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .tour.v1.TourResponse tours = 1;</code>
     */
    private $tours;
    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     */
    protected $total = 0;
    /**
     * Generated from protobuf field <code>int32 page = 3;</code>
     */
    protected $page = 0;
    /**
     * Generated from protobuf field <code>int32 page_size = 4;</code>
     */
    protected $page_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Travel\Proto\Tour\V1\TourResponse>|\Google\Protobuf\Internal\RepeatedField $tours
     *     @type int $total
     *     @type int $page
     *     @type int $page_size
     * }
     */
    public function __construct($data = NULL) {
        \Travel\Proto\Tour\V1\Metadata\Tour::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .tour.v1.TourResponse tours = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTours()
    {
        return $this->tours;
    }

    /**
     * Generated from protobuf field <code>repeated .tour.v1.TourResponse tours = 1;</code>
     * @param array<\Travel\Proto\Tour\V1\TourResponse>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTours($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Travel\Proto\Tour\V1\TourResponse::class);
        $this->tours = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 3;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 4;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

}

