<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tour/v1/tour.proto

namespace Travel\Proto\Tour\V1;

use Spiral\RoadRunner\GRPC\ContextInterface;
use Spiral\RoadRunner\GRPC\ServiceInterface;

/**
 * Service definition for TourService
 */
interface TourServiceInterface extends ServiceInterface
{
    // Service name from proto file: package.service
    public const NAME = 'tour.v1.TourService';

    /**
     * Get a tour by ID
     *
     * @param ContextInterface $ctx
     * @param GetTourByIdRequest $in
     * @return TourResponse
     */
    public function GetTourById(ContextInterface $ctx, GetTourByIdRequest $in): TourResponse;

    /**
     * List tours with pagination
     *
     * @param ContextInterface $ctx
     * @param ListToursRequest $in
     * @return ListToursResponse
     */
    public function ListTours(ContextInterface $ctx, ListToursRequest $in): ListToursResponse;
}
